import type {Metadata} from "next"

import "@/styles/globals.css"
import Navbar from "@/components/layouts/nabvar/Navbar"
import {NextIntlClientProvider} from "next-intl"
import Footer from "@/components/layouts/Footer"
import {geistMono, geistSans, venusRising} from "../fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${venusRising.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <Navbar />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
